In [1]:
# %pylab

import numpy
import matplotlib
from matplotlib import pylab, mlab, pyplot
from mpl_toolkits.mplot3d import Axes3D
np = numpy
plt = pyplot

from pylab import *
from numpy import *

In [2]:
import os
from os import listdir
from os.path import isfile, join

import tkinter as tk
from tkinter import filedialog
%matplotlib qt

from pathlib import Path

In [3]:
from natsort import natsorted   # natural sort marche de ouf
import re                       # find '/' in strings
import timeit
cm = pylab.get_cmap('summer')   # colormap par défaut color=cm(k/len(array))

In [4]:
# Fonctions persos de Jofre et Adrien

# %run function_jofre.ipy
%run ../../Functions/1.2/data_fct_Adrien_point_by_point

matplotlib.rcParams.update({'font.size': 25})

In [5]:
my_order = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,25,26,27,20,21,22,23]

In [6]:
files_to_load = [
    'detection_rate_6eV.npz',
    'detection_rate_10eV.npz',
    'detection_rate_50eV.npz',
    'detection_rate_100eV.npz',
    'detection_rate_1000eV.npz',
]

In [7]:
E0_GMol = [6,10,50,100,1000]
detect_rate = []
mean_std_deltaEc = []

for w,my_E0 in enumerate(E0_GMol):
    outfile = files_to_load[w]
    print(outfile)
    # E0_GMol, detect_rate, mean_std_deltaEc, points_and_coord, Udc,Urf
    with load(outfile, allow_pickle=True) as data:    
        detect_rate.append(list(data['detect_rate']))
        mean_std_deltaEc.append(list(data['mean_std_deltaEc']))
        
with load(outfile, allow_pickle=True) as data:    
    points_and_coord = data['points_and_coord']
print(detect_rate)
print(points_and_coord)

# detect_rate = reshape(detect_rate,(28,4),order='F')

detection_rate_6eV.npz
detection_rate_10eV.npz
detection_rate_50eV.npz
detection_rate_100eV.npz
detection_rate_1000eV.npz
[[0.45, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.3, 1.0, 1.0, 0.0, 0.05, 0.8, 1.0, 0.0, 0.0, 0.7, 1.0, 0.0, 0.0, 0.2, 1.0, 0.0, 0.0, 0.5, 1.0], [0.9523809523809523, 1.0, 1.0, 1.0, 0.09523809523809523, 1.0, 1.0, 1.0, 0.0, 0.6666666666666666, 1.0, 1.0, 0.0, 0.19047619047619047, 1.0, 1.0, 0.0, 0.09523809523809523, 0.5714285714285714, 1.0, 0.0, 0.0, 0.19047619047619047, 1.0, 0.0, 0.0, 0.9523809523809523, 1.0], [0.63, 1.0, 1.0, 1.0, 0.14, 0.99, 1.0, 1.0, 0.0, 0.3, 0.98, 1.0, 0.0, 0.05, 0.71, 1.0, 0.0, 0.31, 0.34, 1.0, 0.0, 0.0, 0.39, 1.0, 0.0, 0.0, 0.86, 0.92], [0.43333333333333335, 1.0, 1.0, 1.0, 0.03333333333333333, 0.9666666666666667, 1.0, 1.0, 0.0, 0.1, 0.8, 1.0, 0.0, 0.0, 0.4, 1.0, 0.0, 0.16666666666666666, 0.1, 0.9333333333333333, 0.0, 0.0, 0.23333333333333334, 0.9333333333333333, 0.0, 0.03333333333333333, 0.7333333333333333, 0.8333333333333334], [0.0, 0.142857142

In [49]:
shape(mean_std_deltaEc)

(5, 28, 4)

In [8]:
# renormalize SNR  :  21,21,100,30,21
renorm_SNR = [1,1,100/21,30/21,1]
for w,my_E0 in enumerate(E0_GMol):
    detect_rate[w] = multiply(asanyarray(detect_rate)[w],renorm_SNR[w])

In [9]:
print(shape(detect_rate))
detect_rate

(5, 28)


[array([0.45, 1.  , 1.  , 1.  , 0.  , 1.  , 1.  , 1.  , 0.  , 0.3 , 1.  ,
        1.  , 0.  , 0.05, 0.8 , 1.  , 0.  , 0.  , 0.7 , 1.  , 0.  , 0.  ,
        0.2 , 1.  , 0.  , 0.  , 0.5 , 1.  ]),
 array([0.95238095, 1.        , 1.        , 1.        , 0.0952381 ,
        1.        , 1.        , 1.        , 0.        , 0.66666667,
        1.        , 1.        , 0.        , 0.19047619, 1.        ,
        1.        , 0.        , 0.0952381 , 0.57142857, 1.        ,
        0.        , 0.        , 0.19047619, 1.        , 0.        ,
        0.        , 0.95238095, 1.        ]),
 array([3.        , 4.76190476, 4.76190476, 4.76190476, 0.66666667,
        4.71428571, 4.76190476, 4.76190476, 0.        , 1.42857143,
        4.66666667, 4.76190476, 0.        , 0.23809524, 3.38095238,
        4.76190476, 0.        , 1.47619048, 1.61904762, 4.76190476,
        0.        , 0.        , 1.85714286, 4.76190476, 0.        ,
        0.        , 4.0952381 , 4.38095238]),
 array([0.61904762, 1.42857143, 1.

In [10]:
points_and_coord = {'DC01_RF08': ['01', '08'], 'DC01_RF09': ['01', '09'], 'DC01_RF10': ['01', '10'], 'DC01_RF11': ['01', '11'],
                    'DC03_RF08': ['03', '08'], 'DC03_RF09': ['03', '09'], 'DC03_RF10': ['03', '10'], 'DC03_RF11': ['03', '11'],
                    'DC05_RF08': ['05', '08'], 'DC05_RF09': ['05', '09'], 'DC05_RF10': ['05', '10'], 'DC05_RF11': ['05', '11'],
                    'DC07_RF08': ['07', '08'], 'DC07_RF09': ['07', '09'], 'DC07_RF10': ['07', '10'], 'DC07_RF11': ['07', '11'], 
                    'DC09_RF08': ['09', '08'], 'DC09_RF09': ['09', '09'], 'DC09_RF10': ['09', '10'], 'DC09_RF11': ['09', '11'],
                    'DC11_RF08': ['11', '08'], 'DC11_RF09': ['11', '09'], 'DC11_RF10': ['11', '10'], 'DC11_RF11': ['11', '11'],
                    'DC18_RF08': ['18', '08'], 'DC18_RF09': ['18', '09'], 'DC18_RF10': ['18', '10'], 'DC18_RF11': ['18', '11']}

In [11]:
# Plot all temp for all conditions
fname = 'detec_efficiency'
cm = pylab.get_cmap('rainbow')

fig, ax = plt.subplots(4, 7,num=fname,clear=True,sharex=True,sharey=True)  # (a,b)
fig.set_size_inches(11.69,8.27)
# suptitle('Saturation 866')

to_plot = 0
my_colors = ['C0','C1','C2','C3','C4']

for l in range(0,7): # b
    for k in range(0,4): # a
        ax[3-k,l].scatter(E0_GMol,asanyarray(detect_rate)[:,my_order[to_plot]],
                           c=[0,1,2,3,4],cmap = 'rainbow',marker='D',edgecolor='black')
        ax[3-k,l].grid(True, which="both")
        ax[3-k,l].annotate(str(list(dict.fromkeys(points_and_coord))[my_order[to_plot]]), xy=(0.02, 0.99), xycoords='axes fraction', # pts_concerned[to_plot]
        size=12, ha='left', va='top',
        bbox=dict(boxstyle='round', fc='C1'))
        to_plot += 1
        if to_plot == 28:
            break
    if to_plot == 28:
        break
ax[3-k,l].grid(True, which="both", ls="-", color='0.65')
ax[3-k,l].yaxis.set_major_locator(matplotlib.ticker.MultipleLocator(base=0.5))
ax[3-k,l].set_xlim(0.8,1750)
ax[3-k,l].set_ylim(-0.1,1.35)

ax[3-k,l].set_xscale('log')
fig.suptitle('Detec_efficiency vs. E0, for each condition')
fig.text(0.56, 0.04, 'E0 [eV]', ha='center')
fig.text(0.04, 0.54, 'detction rate [%]', va='center', rotation='vertical')


# fig.text(0.5, 0.01, 'f', ha='center')
# fig.text(0.01, 0.5, r'$| FFT(HC(t)) | / N_{sample}$', va='center', rotation='vertical')

fig.set_size_inches(11.69,8.27)
plt.tight_layout()
subplots_adjust(hspace=0.05, wspace = 0.05, bottom = 0.120, left = 0.140, top = 0.92) # hspace=0, top=0.95, left = 0.065, bottom = 0.07
savefig(fname+'.png') 

In [39]:
# Plot all temp for all conditions
fname = 'delta_EGMol'
cm = pylab.get_cmap('rainbow')

fig, ax = plt.subplots(4, 7,num=fname,clear=True,sharex=True,sharey=True)  # (a,b)
fig.set_size_inches(11.69,8.27)
# suptitle('Saturation 866')

to_plot = 0

for l in range(0,7): # b
    for k in range(0,4): # a
        ax[3-k,l].errorbar(E0_GMol,multiply(asanyarray(mean_std_deltaEc)[:,my_order[to_plot],2],1000),
                           color='C1',marker='D',markeredgecolor='black',linestyle='--')
        ax[3-k,l].grid(True, which="both")
        plt.xscale('log')
        ax[3-k,l].annotate(str(list(dict.fromkeys(points_and_coord))[my_order[to_plot]]), xy=(0.02, 0.99), xycoords='axes fraction', # pts_concerned[to_plot]
        size=12, ha='left', va='top',
        bbox=dict(boxstyle='round', fc='C1'))
        to_plot += 1
        if to_plot == 28:
            break
    if to_plot == 28:
        break
ax[3-k,l].grid(True, which="both", ls="-", color='0.65')
ax[3-k,l].yaxis.set_major_locator(matplotlib.ticker.MultipleLocator(base=10))
ax[3-k,l].set_xlim(0.8,1900)
ax[3-k,l].set_ylim(-58,12.5)
fig.suptitle('$\Delta$ EGmol vs. E0, for each condition only SNR>1')
fig.text(0.56, 0.04, 'E0 [eV]', ha='center')
fig.text(0.04, 0.54, 'delta_EGMol [meV]', va='center', rotation='vertical')


# fig.text(0.5, 0.01, 'f', ha='center')
# fig.text(0.01, 0.5, r'$| FFT(HC(t)) | / N_{sample}$', va='center', rotation='vertical')

fig.set_size_inches(11.69,8.27)
plt.tight_layout()
subplots_adjust(hspace=0.05, wspace = 0.05, bottom = 0.120, left = 0.140, top = 0.92) # hspace=0, top=0.95, left = 0.065, bottom = 0.07
savefig(fname+'.png') 

In [12]:
to_plot = 3
print(asanyarray(detect_rate)[:,my_order[to_plot]])
my_colors = []
for x,y in enumerate(asanyarray(detect_rate)[:,0]):
    my_colors.append(cm(y))
print(my_colors)

[1.         1.         4.76190476 1.42857143 1.        ]
[(0.4019607843137255, 0.9881654720812594, 0.7594049166547071, 1.0), (1.0, 0.14730169805463766, 0.07385252747487403, 1.0), (1.0, 1.2246467991473532e-16, 6.123233995736766e-17, 1.0), (0.7392156862745098, 0.9302293085467404, 0.5625927516198231, 1.0), (0.5, 0.0, 1.0, 1.0)]


In [13]:
# Plot all temp for all conditions
fname = 'delta_EGMol_allcases'
cm = pylab.get_cmap('rainbow')

fig, ax = plt.subplots(4, 7,num=fname,clear=True,sharex=True,sharey=True)  # (a,b)
fig.set_size_inches(11.69,8.27)
# suptitle('Saturation 866')

to_plot = 0

for l in range(0,7): # b
    for k in range(0,4): # a
        my_colors = []
        for x,y in enumerate(asanyarray(detect_rate)[:,my_order[to_plot]]):
            my_colors.append(cm(y))
        ax[3-k,l].scatter(E0_GMol, multiply(asanyarray(mean_std_deltaEc)[:,my_order[to_plot],0],1000),
                          c=my_colors, s=25, zorder=3,
                         marker='D',edgecolor='black')
        ax[3-k,l].errorbar(E0_GMol,multiply(asanyarray(mean_std_deltaEc)[:,my_order[to_plot],0],1000),
                           yerr=multiply(asanyarray(mean_std_deltaEc)[:,my_order[to_plot],1],1000),
                           zorder=0, fmt="none",marker="none",linestyle='--')
        ax[3-k,l].grid(True, which="both")
        plt.xscale('log')
        ax[3-k,l].annotate(str(list(dict.fromkeys(points_and_coord))[my_order[to_plot]]), xy=(0.02, 0.99), xycoords='axes fraction', # pts_concerned[to_plot]
        size=12, ha='left', va='top',
        bbox=dict(boxstyle='round', fc='C1'))
        to_plot += 1
        if to_plot == 28:
            break
    if to_plot == 28:
        break
ax[3-k,l].grid(True, which="both", ls="-", color='0.65')
ax[3-k,l].yaxis.set_major_locator(matplotlib.ticker.MultipleLocator(base=15))
ax[3-k,l].set_xlim(3,1900)
ax[3-k,l].set_ylim(-55,17.5)
fig.suptitle('$\Delta$EGmol vs. E0, for each condition')
fig.text(0.56, 0.04, 'E0 [eV]', ha='center')
fig.text(0.04, 0.54, '$\Delta$E GMol [meV]', va='center', rotation='vertical')


# fig.text(0.5, 0.01, 'f', ha='center')
# fig.text(0.01, 0.5, r'$| FFT(HC(t)) | / N_{sample}$', va='center', rotation='vertical')

fig.set_size_inches(11.69,8.27)
plt.tight_layout()
subplots_adjust(hspace=0.05, wspace = 0.05, bottom = 0.120, left = 0.140, top = 0.92) # hspace=0, top=0.95, left = 0.065, bottom = 0.07
# savefig(fname+'.png') 

In [14]:
rf = 2
dc = 3
print(shape(mean_std_deltaEc))
# print(asanyarray(mean_std_deltaEc[2][rf]))
print(asanyarray(mean_std_deltaEc[2][rf:28:4][dc])[0])

(5, 28, 4)
-0.010806962407566893


In [15]:
print(asanyarray(mean_std_deltaEc[2][rf:28:4])[0])

[-0.03513065  0.00634761 -0.03513065  0.00634761]


In [16]:
delta_GMol_RFsorted = []
std_delta_GMol_RFsorted = []

for rf in range(4):
    delta_GMol_RFsorted.append([])
    std_delta_GMol_RFsorted.append([])
    for dc in range(7):
        delta_GMol_RFsorted[rf].append([])
        std_delta_GMol_RFsorted[rf].append([])
        for egmol in range(5):
            test = asanyarray(mean_std_deltaEc[egmol][rf:28:4][dc])[0]
            delta_GMol_RFsorted[rf][dc].append(test)
            test = asanyarray(mean_std_deltaEc[egmol][rf:28:4][dc])[1]
            std_delta_GMol_RFsorted[rf][dc].append(test)
# print(delta_GMol_RFsorted)
print(shape(delta_GMol_RFsorted),shape(std_delta_GMol_RFsorted))

(4, 7, 5) (4, 7, 5)


In [17]:
rf = 2
dc = 6
E0_GMol, list(multiply(delta_GMol_RFsorted[rf][dc][:],1000))

([6, 10, 50, 100, 1000],
 [-9.899718431667244,
  -13.62339895456808,
  -18.218578956575527,
  -16.314752363929426,
  -4.91339811554306])

In [18]:
my_order_dc = [0,1,2,3,4,6,5]
Urf = [53.85, 59.23, 64.61, 70.00]

In [19]:
import matplotlib.gridspec as gridspec

In [21]:
# Plot all delta EGmol sorted by RF
fname = 'delta_EGMol_rfsorted_gridspec'
cm = pylab.get_cmap('cividis')

fig = plt.figure(num=fname,clear=True)
fig.set_size_inches(11.69,8.27)
gs1 = gridspec.GridSpec(2, 2)
gs1.update(left=0.13, right=0.88, top=0.98, bottom=0.180, wspace=0, hspace = 0)

gs2 = gridspec.GridSpec(1, 1)
gs2.update(left=0.89, right=0.92, top=0.98, wspace=0, hspace = 0)

to_plot = 0

my_marker = ['v','s','p','H']
my_size = [10,7.5,10,10]

ax1 = plt.subplot(gs1[0])
for rf in range(4): # rf
    k = rf //2
    l = rf%2
    ax = plt.subplot(gs1[to_plot],sharex=ax1,sharey=ax1)
    for dc in range(7):
        
        ax.semilogx(E0_GMol, list(multiply(delta_GMol_RFsorted[rf][my_order_dc[dc]][:],1000)), # [:,my_order[to_plot],0]
                          c=cm(dc/6), ms=my_size[rf], zorder=3,mec='black',marker=my_marker[rf],
                          ls='--')
        ax.errorbar(E0_GMol,list(multiply(delta_GMol_RFsorted[rf][my_order_dc[dc]][:],1000)),
                           yerr=list(multiply(std_delta_GMol_RFsorted[rf][my_order_dc[dc]][:],1000)),
                           zorder=0, fmt="none",marker="none",
                           color=cm(dc/6),lw=2)
        ax.grid(True)
        ax.annotate('$U_{RF}$ = ' + f'{Urf[rf]} V',(3.6,5.75),
                    size=20, ha='left', va='top',
                    bbox=dict(boxstyle='round', fc='white'))
    # Get current tick locations and append 271 to this array
    # x_ticks = np.append(ax.get_xticks(), 50)
    # Set xtick locations to the values of the array `x_ticks`
    ax.set_xticks([6,10,50,100,1000])
    ax.set_xticklabels([6,10,50,100,r'$10^3$'],rotation=45)
#     ax[k,l].annotate(str(list(dict.fromkeys(points_and_coord))[my_order[to_plot]]), xy=(0.02, 0.99), xycoords='axes fraction', # pts_concerned[to_plot]
#     size=12, ha='left', va='top',
#     bbox=dict(boxstyle='round', fc='C1'))

    if l==1:
        ax.tick_params(labelleft=False,left=False)
    to_plot += 1
        
# ax.grid(True, which="both", ls="-", color='0.65')
ax.yaxis.set_major_locator(matplotlib.ticker.MultipleLocator(base=10))
ax.set_xlim(3,1900)
ax.set_ylim(-52,8)
# fig.suptitle('$\Delta$EGmol vs. E0, for each condition')
fig.text(0.5, 0.04, '$E_0$ SUI [eV]', ha='center')
fig.text(0.02, 0.54, '$\Delta$E SUI [meV]', va='center', rotation='vertical')


# subplots_adjust(hspace=0.0, wspace = 0.0, bottom = 0.120, left = 0.140, right = 0.90, top = 0.92) # hspace=0, top=0.95, left = 0.065, bottom = 0.07

#######################################################

axb = plt.subplot(gs2[0])
cmap = mpl.colors.ListedColormap([cm(k/6) for k in range(7)])
bounds = [0.5,1.5,2.5,3.5,4.5,5.5,6.5,7.5]
norm = mpl.colors.BoundaryNorm(bounds, cmap.N)
cb2 = mpl.colorbar.ColorbarBase(axb, cmap=cmap,
                                norm=norm,
                                ticks=np.arange(1,8), # np.arange(0.5,7.5)
                                spacing='proportional',
                                orientation='vertical')
cb2.set_label('$U_{DC}$ [V]')

######################################################


savefig(fname+'.png',dpi=300)
savefig(fname+'.eps',dpi=600,format='eps')